name: 'dbts'
version: '1.0.0'

profile: 'dbts'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbts:
    +on_table_exists: drop
    staging:
      +schema: staging
      +materialized: view
    mart:
      +schema: mart
      +materialized: table

  elementary:
    +schema: elementary