version: 2

models:
  - name:  bacnk_marketing
    columns:

      - name: listing_id
        tests: 
          - unique
          - not_null
          - relations:
              to: ref('dim_hosts_cleansed')
              field: host_id


      - name: root_type
        tests:
          - accepted_values:
              values: ['a', 'b', 'c']