SELECT SUM(CASE
            WHEN DT.VALUE_BEING_CHECKED IS NOT NULL THEN 1
            ELSE 0
            END) * 1.0 / COUNT(*) AS PERCENTAGE_ROWS_IN_RANGE
        , DATA_QUALITY_CHECK_NAME
FROM SOURCE_TABLE_ST ST
LEFT JOIN DATA_QUALITY_CATEGORY_CHECK_TABLE DT
ON ST.STATE_ABBREVIATION = DT.VALUE_BEING_CHECKED
WHERE DATA_QUALITY_CHECK_NAME = 'STATE ABBREVIATION CHECK'
