SELECT 
    SUM(CASE
        WHEN VALUE_BEING_CHECKED BETWEEN LOWER_BOUND AND UPPER_BOUND THEN 1
        ELSE 0
        END) AS * 1.0 / COUNT(*) AS PERCENTAGE_ROWS_IN_RANGE
    , DATA_QUALITY_CHECK_NAME
FROM SOURCE_TABLE_ST
LEFT JOIN DATA_QUALITY_CHECK_TABLE DT
    ON 1=1
WHERE
    DATA_QUALITY_CHECK_NAME = 'RANGE OF XYZ FIELD '